apiVersion: integration/v1
kind: Step
name: azure-disks-step-disk-list
version: 1
summary: Step template

description: |
  This is a template for a simple step.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/azure-disks-step-disk-list
