apiVersion: integration/v1
kind: Step
name: azure-disks-step-disk-delete
version: 1
summary: Delete disks

description: |
  This step container deletes a set of Azure disks in an Azure subscription given a list of resource IDs.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/azure-disks-step-disk-delete
