apiVersion: integration/v1
kind: Step
name: azure-disks-step-disk-delete
version: 1
summary: Delete disks

description: |
  This step container deletes a set of Azure disks in an Azure subscription given a list of resource IDs.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/azure-disks-step-disk-delete

schemas:
  spec:
    source: file
    file: spec.schema.json

examples:
- summary: Delete Azure disk
  content:
    apiVersion: v1
    kind: Step
    name: azure-disks-delete-disk
    image: relaysh/azure-disks-step-disk-delete
    spec:
      azure:
        connection: !Connection { type: azure, name: my-azure-account }
      resourceIDs:
      - !Parameter resourceID